version: 2

# See https://golangci-lint.run/usage/linters/ for a list of linters.
linters:
  disable-all: true
  enable:
    - err113
    - gosec
    - errcheck
    - nilnil
    - nilerr
    - staticcheck
