// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type AlertSeverity string

const (
	AlertSeverityCritical AlertSeverity = "CRITICAL"
	AlertSeverityInfo     AlertSeverity = "INFO"
	AlertSeverityWarning  AlertSeverity = "WARNING"
)

type ConditionType string

const (
	ConditionTypeEntityMetric     ConditionType = "ENTITY_METRIC"
	ConditionTypeLogQuery         ConditionType = "LOG_QUERY"
	ConditionTypeStandaloneMetric ConditionType = "STANDALONE_METRIC"
	ConditionTypeUnknown          ConditionType = "UNKNOWN"
)

// CreateAlertDefinitionAlertMutations includes the requested fields of the GraphQL type AlertMutations.
type CreateAlertDefinitionAlertMutations struct {
	CreateAlertDefinition CreateAlertDefinitionAlertMutationsCreateAlertDefinition `json:"createAlertDefinition"`
}

// GetCreateAlertDefinition returns CreateAlertDefinitionAlertMutations.CreateAlertDefinition, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutations) GetCreateAlertDefinition() CreateAlertDefinitionAlertMutationsCreateAlertDefinition {
	return v.CreateAlertDefinition
}

// CreateAlertDefinitionAlertMutationsCreateAlertDefinition includes the requested fields of the GraphQL type AlertDefinition.
type CreateAlertDefinitionAlertMutationsCreateAlertDefinition struct {
	Id                  string                                                                                              `json:"id"`
	OrganizationId      string                                                                                              `json:"organizationId"`
	Name                string                                                                                              `json:"name"`
	Description         string                                                                                              `json:"description"`
	Severity            AlertSeverity                                                                                       `json:"severity"`
	Enabled             bool                                                                                                `json:"enabled"`
	ConditionType       ConditionType                                                                                       `json:"conditionType"`
	ConditionUpdatedAt  string                                                                                              `json:"conditionUpdatedAt"`
	FlatCondition       []CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression `json:"flatCondition"`
	Actions             []CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction                        `json:"actions"`
	TriggerResetActions bool                                                                                                `json:"triggerResetActions"`
}

// GetId returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Id, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetId() string { return v.Id }

// GetOrganizationId returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.OrganizationId, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetOrganizationId() string {
	return v.OrganizationId
}

// GetName returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Name, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetName() string { return v.Name }

// GetDescription returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Description, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetDescription() string {
	return v.Description
}

// GetSeverity returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Severity, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetSeverity() AlertSeverity {
	return v.Severity
}

// GetEnabled returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Enabled, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetEnabled() bool {
	return v.Enabled
}

// GetConditionType returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.ConditionType, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetConditionType() ConditionType {
	return v.ConditionType
}

// GetConditionUpdatedAt returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.ConditionUpdatedAt, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetConditionUpdatedAt() string {
	return v.ConditionUpdatedAt
}

// GetFlatCondition returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.FlatCondition, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetFlatCondition() []CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression {
	return v.FlatCondition
}

// GetActions returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Actions, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetActions() []CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction {
	return v.Actions
}

// GetTriggerResetActions returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.TriggerResetActions, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetTriggerResetActions() bool {
	return v.TriggerResetActions
}

// CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction includes the requested fields of the GraphQL type AlertAction.
type CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction struct {
	Type             string   `json:"type"`
	ConfigurationIds []string `json:"configurationIds"`
}

// GetType returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction.Type, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction) GetType() string {
	return v.Type
}

// GetConfigurationIds returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction.ConfigurationIds, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction) GetConfigurationIds() []string {
	return v.ConfigurationIds
}

// CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression includes the requested fields of the GraphQL type FlatAlertConditionExpression.
type CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression struct {
	Id    string                                                                                                                       `json:"id"`
	Links []CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks           `json:"links"`
	Value CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode `json:"value"`
}

// GetId returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression.Id, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression) GetId() string {
	return v.Id
}

// GetLinks returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression.Links, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression) GetLinks() []CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks {
	return v.Links
}

// GetValue returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression.Value, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression) GetValue() CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode {
	return v.Value
}

// CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks includes the requested fields of the GraphQL type NamedLinks.
type CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks struct {
	Name   string   `json:"name"`
	Values []string `json:"values"`
}

// GetName returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks.Name, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks) GetName() string {
	return v.Name
}

// GetValues returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks.Values, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks) GetValues() []string {
	return v.Values
}

// CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode includes the requested fields of the GraphQL type FlatAlertConditionNode.
type CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode struct {
	Type         string                                                                                                                                   `json:"type"`
	Operator     string                                                                                                                                   `json:"operator"`
	EntityFilter CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter `json:"entityFilter"`
	FieldName    string                                                                                                                                   `json:"fieldName"`
	DataType     string                                                                                                                                   `json:"dataType"`
	Value        string                                                                                                                                   `json:"value"`
	Query        string                                                                                                                                   `json:"query"`
	Source       string                                                                                                                                   `json:"source"`
}

// GetType returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Type, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetType() string {
	return v.Type
}

// GetOperator returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Operator, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetOperator() string {
	return v.Operator
}

// GetEntityFilter returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.EntityFilter, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetEntityFilter() CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter {
	return v.EntityFilter
}

// GetFieldName returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.FieldName, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetFieldName() string {
	return v.FieldName
}

// GetDataType returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.DataType, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetDataType() string {
	return v.DataType
}

// GetValue returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Value, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetValue() string {
	return v.Value
}

// GetQuery returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Query, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetQuery() string {
	return v.Query
}

// GetSource returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Source, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetSource() string {
	return v.Source
}

// CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter includes the requested fields of the GraphQL type AlertConditionNodeEntityFilter.
type CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter struct {
	Type string `json:"type"`
}

// GetType returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter.Type, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter) GetType() string {
	return v.Type
}

// CreateAlertDefinitionResponse is returned by CreateAlertDefinition on success.
type CreateAlertDefinitionResponse struct {
	AlertMutations CreateAlertDefinitionAlertMutations `json:"alertMutations"`
}

// GetAlertMutations returns CreateAlertDefinitionResponse.AlertMutations, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionResponse) GetAlertMutations() CreateAlertDefinitionAlertMutations {
	return v.AlertMutations
}

// DeleteAlertDefinitionAlertMutations includes the requested fields of the GraphQL type AlertMutations.
type DeleteAlertDefinitionAlertMutations struct {
	DeleteAlertDefinition string `json:"deleteAlertDefinition"`
}

// GetDeleteAlertDefinition returns DeleteAlertDefinitionAlertMutations.DeleteAlertDefinition, and is useful for accessing the field via an interface.
func (v *DeleteAlertDefinitionAlertMutations) GetDeleteAlertDefinition() string {
	return v.DeleteAlertDefinition
}

// DeleteAlertDefinitionResponse is returned by DeleteAlertDefinition on success.
type DeleteAlertDefinitionResponse struct {
	AlertMutations DeleteAlertDefinitionAlertMutations `json:"alertMutations"`
}

// GetAlertMutations returns DeleteAlertDefinitionResponse.AlertMutations, and is useful for accessing the field via an interface.
func (v *DeleteAlertDefinitionResponse) GetAlertMutations() DeleteAlertDefinitionAlertMutations {
	return v.AlertMutations
}

type FilterOperation string

const (
	FilterOperationAnd      FilterOperation = "AND"
	FilterOperationContains FilterOperation = "CONTAINS"
	FilterOperationEq       FilterOperation = "EQ"
	FilterOperationExists   FilterOperation = "EXISTS"
	FilterOperationGe       FilterOperation = "GE"
	FilterOperationGt       FilterOperation = "GT"
	FilterOperationIn       FilterOperation = "IN"
	FilterOperationLe       FilterOperation = "LE"
	FilterOperationLt       FilterOperation = "LT"
	FilterOperationMatches  FilterOperation = "MATCHES"
	FilterOperationNe       FilterOperation = "NE"
	FilterOperationNot      FilterOperation = "NOT"
	FilterOperationOr       FilterOperation = "OR"
)

// GetAlertAlertQueries includes the requested fields of the GraphQL type AlertQueries.
type GetAlertAlertQueries struct {
	AlertDefinitions GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResult `json:"alertDefinitions"`
}

// GetAlertDefinitions returns GetAlertAlertQueries.AlertDefinitions, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueries) GetAlertDefinitions() GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResult {
	return v.AlertDefinitions
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResult includes the requested fields of the GraphQL type AlertDefinitionsResult.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResult struct {
	AlertDefinitions []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition `json:"alertDefinitions"`
}

// GetAlertDefinitions returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResult.AlertDefinitions, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResult) GetAlertDefinitions() []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition {
	return v.AlertDefinitions
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition includes the requested fields of the GraphQL type AlertDefinition.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition struct {
	Id                  string                                                                                                                               `json:"id"`
	OrganizationId      string                                                                                                                               `json:"organizationId"`
	Name                string                                                                                                                               `json:"name"`
	Description         string                                                                                                                               `json:"description"`
	Severity            AlertSeverity                                                                                                                        `json:"severity"`
	Enabled             bool                                                                                                                                 `json:"enabled"`
	MuteInfo            GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo                                    `json:"muteInfo"`
	Triggered           bool                                                                                                                                 `json:"triggered"`
	ConditionType       ConditionType                                                                                                                        `json:"conditionType"`
	ConditionUpdatedAt  string                                                                                                                               `json:"conditionUpdatedAt"`
	FlatCondition       []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression `json:"flatCondition"`
	Actions             []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction                        `json:"actions"`
	TriggerResetActions bool                                                                                                                                 `json:"triggerResetActions"`
}

// GetId returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Id, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetId() string {
	return v.Id
}

// GetOrganizationId returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.OrganizationId, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetOrganizationId() string {
	return v.OrganizationId
}

// GetName returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Name, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetName() string {
	return v.Name
}

// GetDescription returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Description, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetDescription() string {
	return v.Description
}

// GetSeverity returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Severity, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetSeverity() AlertSeverity {
	return v.Severity
}

// GetEnabled returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Enabled, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetEnabled() bool {
	return v.Enabled
}

// GetMuteInfo returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.MuteInfo, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetMuteInfo() GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo {
	return v.MuteInfo
}

// GetTriggered returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Triggered, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetTriggered() bool {
	return v.Triggered
}

// GetConditionType returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.ConditionType, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetConditionType() ConditionType {
	return v.ConditionType
}

// GetConditionUpdatedAt returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.ConditionUpdatedAt, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetConditionUpdatedAt() string {
	return v.ConditionUpdatedAt
}

// GetFlatCondition returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.FlatCondition, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetFlatCondition() []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression {
	return v.FlatCondition
}

// GetActions returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Actions, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetActions() []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction {
	return v.Actions
}

// GetTriggerResetActions returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.TriggerResetActions, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetTriggerResetActions() bool {
	return v.TriggerResetActions
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction includes the requested fields of the GraphQL type AlertAction.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction struct {
	Type             string   `json:"type"`
	ConfigurationIds []string `json:"configurationIds"`
}

// GetType returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction.Type, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction) GetType() string {
	return v.Type
}

// GetConfigurationIds returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction.ConfigurationIds, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction) GetConfigurationIds() []string {
	return v.ConfigurationIds
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression includes the requested fields of the GraphQL type FlatAlertConditionExpression.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression struct {
	Id    string                                                                                                                                                        `json:"id"`
	Links []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks           `json:"links"`
	Value GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode `json:"value"`
}

// GetId returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression.Id, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression) GetId() string {
	return v.Id
}

// GetLinks returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression.Links, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression) GetLinks() []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks {
	return v.Links
}

// GetValue returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression.Value, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression) GetValue() GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode {
	return v.Value
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks includes the requested fields of the GraphQL type NamedLinks.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks struct {
	Name   string   `json:"name"`
	Values []string `json:"values"`
}

// GetName returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks.Name, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks) GetName() string {
	return v.Name
}

// GetValues returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks.Values, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks) GetValues() []string {
	return v.Values
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode includes the requested fields of the GraphQL type FlatAlertConditionNode.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode struct {
	Type         string                                                                                                                                                                                               `json:"type"`
	Operator     string                                                                                                                                                                                               `json:"operator"`
	EntityFilter GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter                            `json:"entityFilter"`
	DataType     string                                                                                                                                                                                               `json:"dataType"`
	FieldName    string                                                                                                                                                                                               `json:"fieldName"`
	Value        string                                                                                                                                                                                               `json:"value"`
	MetricFilter []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpression `json:"metricFilter"`
	Source       string                                                                                                                                                                                               `json:"source"`
	Query        string                                                                                                                                                                                               `json:"query"`
}

// GetType returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Type, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetType() string {
	return v.Type
}

// GetOperator returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Operator, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetOperator() string {
	return v.Operator
}

// GetEntityFilter returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.EntityFilter, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetEntityFilter() GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter {
	return v.EntityFilter
}

// GetDataType returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.DataType, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetDataType() string {
	return v.DataType
}

// GetFieldName returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.FieldName, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetFieldName() string {
	return v.FieldName
}

// GetValue returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Value, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetValue() string {
	return v.Value
}

// GetMetricFilter returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.MetricFilter, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetMetricFilter() []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpression {
	return v.MetricFilter
}

// GetSource returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Source, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetSource() string {
	return v.Source
}

// GetQuery returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Query, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetQuery() string {
	return v.Query
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter includes the requested fields of the GraphQL type AlertConditionNodeEntityFilter.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter struct {
	Type string   `json:"type"`
	Ids  []string `json:"ids"`
}

// GetType returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter.Type, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter) GetType() string {
	return v.Type
}

// GetIds returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter.Ids, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeEntityFilter) GetIds() []string {
	return v.Ids
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpression includes the requested fields of the GraphQL type FlatAlertFilterExpression.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpression struct {
	Id    string                                                                                                                                                                                                                       `json:"id"`
	Links []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionLinksNamedLinks          `json:"links"`
	Value GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression `json:"value"`
}

// GetId returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpression.Id, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpression) GetId() string {
	return v.Id
}

// GetLinks returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpression.Links, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpression) GetLinks() []GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionLinksNamedLinks {
	return v.Links
}

// GetValue returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpression.Value, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpression) GetValue() GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression {
	return v.Value
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionLinksNamedLinks includes the requested fields of the GraphQL type NamedLinks.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionLinksNamedLinks struct {
	Name   string   `json:"name"`
	Values []string `json:"values"`
}

// GetName returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionLinksNamedLinks.Name, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionLinksNamedLinks) GetName() string {
	return v.Name
}

// GetValues returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionLinksNamedLinks.Values, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionLinksNamedLinks) GetValues() []string {
	return v.Values
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression includes the requested fields of the GraphQL type AlertFilterExpression.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression struct {
	Operation      FilterOperation `json:"operation"`
	PropertyValue  string          `json:"propertyValue"`
	PropertyValues []string        `json:"propertyValues"`
	PropertyName   string          `json:"propertyName"`
}

// GetOperation returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression.Operation, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression) GetOperation() FilterOperation {
	return v.Operation
}

// GetPropertyValue returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression.PropertyValue, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression) GetPropertyValue() string {
	return v.PropertyValue
}

// GetPropertyValues returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression.PropertyValues, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression) GetPropertyValues() []string {
	return v.PropertyValues
}

// GetPropertyName returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression.PropertyName, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNodeMetricFilterFlatAlertFilterExpressionValueAlertFilterExpression) GetPropertyName() string {
	return v.PropertyName
}

// GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo includes the requested fields of the GraphQL type AlertDefinitionMuteInfo.
type GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo struct {
	Muted bool   `json:"muted"`
	Until string `json:"until"`
}

// GetMuted returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo.Muted, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo) GetMuted() bool {
	return v.Muted
}

// GetUntil returns GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo.Until, and is useful for accessing the field via an interface.
func (v *GetAlertAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo) GetUntil() string {
	return v.Until
}

// GetAlertResponse is returned by GetAlert on success.
type GetAlertResponse struct {
	AlertQueries GetAlertAlertQueries `json:"alertQueries"`
}

// GetAlertQueries returns GetAlertResponse.AlertQueries, and is useful for accessing the field via an interface.
func (v *GetAlertResponse) GetAlertQueries() GetAlertAlertQueries { return v.AlertQueries }

// UpdateAlertDefinitionAlertMutations includes the requested fields of the GraphQL type AlertMutations.
type UpdateAlertDefinitionAlertMutations struct {
	UpdateAlertDefinition UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition `json:"updateAlertDefinition"`
}

// GetUpdateAlertDefinition returns UpdateAlertDefinitionAlertMutations.UpdateAlertDefinition, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutations) GetUpdateAlertDefinition() UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition {
	return v.UpdateAlertDefinition
}

// UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition includes the requested fields of the GraphQL type AlertDefinition.
type UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition struct {
	Id                  string                                                                       `json:"id"`
	OrganizationId      string                                                                       `json:"organizationId"`
	Name                string                                                                       `json:"name"`
	Description         string                                                                       `json:"description"`
	Severity            AlertSeverity                                                                `json:"severity"`
	Enabled             bool                                                                         `json:"enabled"`
	ConditionType       ConditionType                                                                `json:"conditionType"`
	ConditionUpdatedAt  string                                                                       `json:"conditionUpdatedAt"`
	Actions             []UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction `json:"actions"`
	TriggerResetActions bool                                                                         `json:"triggerResetActions"`
}

// GetId returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Id, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetId() string { return v.Id }

// GetOrganizationId returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.OrganizationId, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetOrganizationId() string {
	return v.OrganizationId
}

// GetName returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Name, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetName() string { return v.Name }

// GetDescription returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Description, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetDescription() string {
	return v.Description
}

// GetSeverity returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Severity, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetSeverity() AlertSeverity {
	return v.Severity
}

// GetEnabled returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Enabled, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetEnabled() bool {
	return v.Enabled
}

// GetConditionType returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.ConditionType, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetConditionType() ConditionType {
	return v.ConditionType
}

// GetConditionUpdatedAt returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.ConditionUpdatedAt, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetConditionUpdatedAt() string {
	return v.ConditionUpdatedAt
}

// GetActions returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Actions, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetActions() []UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction {
	return v.Actions
}

// GetTriggerResetActions returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.TriggerResetActions, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetTriggerResetActions() bool {
	return v.TriggerResetActions
}

// UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction includes the requested fields of the GraphQL type AlertAction.
type UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction struct {
	Type             string   `json:"type"`
	ConfigurationIds []string `json:"configurationIds"`
}

// GetType returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction.Type, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction) GetType() string {
	return v.Type
}

// GetConfigurationIds returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction.ConfigurationIds, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction) GetConfigurationIds() []string {
	return v.ConfigurationIds
}

// UpdateAlertDefinitionResponse is returned by UpdateAlertDefinition on success.
type UpdateAlertDefinitionResponse struct {
	AlertMutations UpdateAlertDefinitionAlertMutations `json:"alertMutations"`
}

// GetAlertMutations returns UpdateAlertDefinitionResponse.AlertMutations, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionResponse) GetAlertMutations() UpdateAlertDefinitionAlertMutations {
	return v.AlertMutations
}

func CreateAlertDefinition(
	ctx context.Context,
	client graphql.Client,
) (*CreateAlertDefinitionResponse, error) {
	req := &graphql.Request{
		OpName: "CreateAlertDefinition",
		Query: `
mutation CreateAlertDefinition {
	alertMutations {
		createAlertDefinition(definition: {name:"Metric alert",severity:INFO,enabled:true,condition:[{id:0,type:"logicalOperator",operator:"OR",operandIds:[1,6]},{id:1,type:"binaryOperator",operator:"<",operandIds:[2,5]},{id:2,type:"aggregationOperator",operator:"AVG",operandIds:[3,4]},{id:3,type:"metricField",entityFilter:{type:"Website"},fieldName:"healthscore"},{id:4,type:"constantValue",dataType:"string",value:"10m"},{id:5,type:"constantValue",dataType:"number",value:"70"},{id:6,type:"binaryOperator",operator:">",operandIds:[7,10]},{id:7,type:"aggregationOperator",operator:"AVG",operandIds:[8,9]},{id:8,type:"metricField",entityFilter:{type:"Website",ids:["e-1415678067767222272"]},fieldName:"synthetics.https.response.time",metricFilter:{operation:NOT,children:{propertyName:"tagName",propertyValue:"tagValue",operation:EQ}}},{id:9,type:"constantValue",dataType:"string",value:"5m"},{id:10,type:"constantValue",dataType:"number",value:"100"}],actions:[{type:"slack",configurationIds:["notification-id-1"]}],triggerResetActions:true}) {
			id
			organizationId
			name
			description
			severity
			enabled
			conditionType
			conditionUpdatedAt
			flatCondition {
				id
				links {
					name
					values
				}
				value {
					type
					operator
					entityFilter {
						type
					}
					fieldName
					dataType
					value
					query
					source
				}
			}
			actions {
				type
				configurationIds
			}
			triggerResetActions
		}
	}
}
`,
	}
	var err error

	var data CreateAlertDefinitionResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func DeleteAlertDefinition(
	ctx context.Context,
	client graphql.Client,
) (*DeleteAlertDefinitionResponse, error) {
	req := &graphql.Request{
		OpName: "DeleteAlertDefinition",
		Query: `
mutation DeleteAlertDefinition {
	alertMutations {
		deleteAlertDefinition(id: "246f719b-d160-4222-97e2-e9ced2203a8a")
	}
}
`,
	}
	var err error

	var data DeleteAlertDefinitionResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetAlert(
	ctx context.Context,
	client graphql.Client,
) (*GetAlertResponse, error) {
	req := &graphql.Request{
		OpName: "GetAlert",
		Query: `
query GetAlert {
	alertQueries {
		alertDefinitions(filter: {id:"0bc4710d-e3b0-4590-9c9b-e5e46d81d912"}) {
			alertDefinitions {
				id
				organizationId
				name
				description
				severity
				enabled
				muteInfo {
					muted
					until
				}
				triggered
				conditionType
				conditionUpdatedAt
				flatCondition {
					id
					links {
						name
						values
					}
					value {
						type
						operator
						entityFilter {
							type
							ids
						}
						dataType
						fieldName
						value
						metricFilter {
							id
							links {
								name
								values
							}
							value {
								operation
								propertyValue
								propertyValues
								propertyName
							}
						}
						source
						query
					}
				}
				actions {
					type
					configurationIds
				}
				triggerResetActions
			}
		}
	}
}
`,
	}
	var err error

	var data GetAlertResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func UpdateAlertDefinition(
	ctx context.Context,
	client graphql.Client,
) (*UpdateAlertDefinitionResponse, error) {
	req := &graphql.Request{
		OpName: "UpdateAlertDefinition",
		Query: `
mutation UpdateAlertDefinition {
	alertMutations {
		updateAlertDefinition(id: "246f719b-d160-4222-97e2-e9ced2203a8a", definition: {name:"My modified alert",description:"Modified description",severity:INFO,enabled:true,condition:[{id:0,type:"binaryOperator",operator:"<",operandIds:[1,4]},{id:1,type:"aggregationOperator",operator:"AVG",operandIds:[2,3]},{id:2,type:"metricField",entityFilter:{type:"Website"},fieldName:"healthscore"},{id:3,type:"constantValue",dataType:"string",value:"10m"},{id:4,type:"constantValue",dataType:"number",value:"70"}],actions:[{type:"slack",configurationIds:["notification-id-1"]}],triggerResetActions:false}) {
			id
			organizationId
			name
			description
			severity
			enabled
			conditionType
			conditionUpdatedAt
			actions {
				type
				configurationIds
			}
			triggerResetActions
		}
	}
}
`,
	}
	var err error

	var data UpdateAlertDefinitionResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
