// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type AlertActionInput struct {
	ConfigurationIds []string `json:"configurationIds"`
	Type             string   `json:"type"`
}

// GetConfigurationIds returns AlertActionInput.ConfigurationIds, and is useful for accessing the field via an interface.
func (v *AlertActionInput) GetConfigurationIds() []string { return v.ConfigurationIds }

// GetType returns AlertActionInput.Type, and is useful for accessing the field via an interface.
func (v *AlertActionInput) GetType() string { return v.Type }

type AlertConditionMatchFieldRuleInput struct {
	FieldName string                         `json:"fieldName"`
	Rules     []AlertConditionMatchRuleInput `json:"rules"`
}

// GetFieldName returns AlertConditionMatchFieldRuleInput.FieldName, and is useful for accessing the field via an interface.
func (v *AlertConditionMatchFieldRuleInput) GetFieldName() string { return v.FieldName }

// GetRules returns AlertConditionMatchFieldRuleInput.Rules, and is useful for accessing the field via an interface.
func (v *AlertConditionMatchFieldRuleInput) GetRules() []AlertConditionMatchRuleInput { return v.Rules }

type AlertConditionMatchRuleInput struct {
	Negate bool                        `json:"negate"`
	Type   AlertConditionMatchRuleType `json:"type"`
	Value  string                      `json:"value"`
}

// GetNegate returns AlertConditionMatchRuleInput.Negate, and is useful for accessing the field via an interface.
func (v *AlertConditionMatchRuleInput) GetNegate() bool { return v.Negate }

// GetType returns AlertConditionMatchRuleInput.Type, and is useful for accessing the field via an interface.
func (v *AlertConditionMatchRuleInput) GetType() AlertConditionMatchRuleType { return v.Type }

// GetValue returns AlertConditionMatchRuleInput.Value, and is useful for accessing the field via an interface.
func (v *AlertConditionMatchRuleInput) GetValue() string { return v.Value }

type AlertConditionMatchRuleType string

const (
	AlertConditionMatchRuleTypeContains AlertConditionMatchRuleType = "CONTAINS"
	AlertConditionMatchRuleTypeEq       AlertConditionMatchRuleType = "EQ"
	AlertConditionMatchRuleTypeMatches  AlertConditionMatchRuleType = "MATCHES"
	AlertConditionMatchRuleTypeNe       AlertConditionMatchRuleType = "NE"
)

type AlertConditionNodeEntityFilterInput struct {
	Fields []AlertConditionMatchFieldRuleInput `json:"fields"`
	Ids    []string                            `json:"ids"`
	Type   string                              `json:"type"`
	Types  []string                            `json:"types"`
}

// GetFields returns AlertConditionNodeEntityFilterInput.Fields, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeEntityFilterInput) GetFields() []AlertConditionMatchFieldRuleInput {
	return v.Fields
}

// GetIds returns AlertConditionNodeEntityFilterInput.Ids, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeEntityFilterInput) GetIds() []string { return v.Ids }

// GetType returns AlertConditionNodeEntityFilterInput.Type, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeEntityFilterInput) GetType() string { return v.Type }

// GetTypes returns AlertConditionNodeEntityFilterInput.Types, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeEntityFilterInput) GetTypes() []string { return v.Types }

type AlertConditionNodeInput struct {
	DataType     string                              `json:"dataType"`
	EntityFilter AlertConditionNodeEntityFilterInput `json:"entityFilter"`
	FieldName    string                              `json:"fieldName"`
	Id           int                                 `json:"id"`
	MetricFilter AlertFilterExpressionInput          `json:"metricFilter"`
	OperandIds   []int                               `json:"operandIds"`
	Operator     string                              `json:"operator"`
	Query        string                              `json:"query"`
	Source       string                              `json:"source"`
	Type         string                              `json:"type"`
	Value        string                              `json:"value"`
}

// GetDataType returns AlertConditionNodeInput.DataType, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetDataType() string { return v.DataType }

// GetEntityFilter returns AlertConditionNodeInput.EntityFilter, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetEntityFilter() AlertConditionNodeEntityFilterInput {
	return v.EntityFilter
}

// GetFieldName returns AlertConditionNodeInput.FieldName, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetFieldName() string { return v.FieldName }

// GetId returns AlertConditionNodeInput.Id, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetId() int { return v.Id }

// GetMetricFilter returns AlertConditionNodeInput.MetricFilter, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetMetricFilter() AlertFilterExpressionInput { return v.MetricFilter }

// GetOperandIds returns AlertConditionNodeInput.OperandIds, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetOperandIds() []int { return v.OperandIds }

// GetOperator returns AlertConditionNodeInput.Operator, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetOperator() string { return v.Operator }

// GetQuery returns AlertConditionNodeInput.Query, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetQuery() string { return v.Query }

// GetSource returns AlertConditionNodeInput.Source, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetSource() string { return v.Source }

// GetType returns AlertConditionNodeInput.Type, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetType() string { return v.Type }

// GetValue returns AlertConditionNodeInput.Value, and is useful for accessing the field via an interface.
func (v *AlertConditionNodeInput) GetValue() string { return v.Value }

type AlertDefinitionInput struct {
	Actions             []AlertActionInput        `json:"actions"`
	Condition           []AlertConditionNodeInput `json:"condition"`
	Description         string                    `json:"description"`
	Enabled             bool                      `json:"enabled"`
	Name                string                    `json:"name"`
	Severity            AlertSeverity             `json:"severity"`
	TriggerResetActions bool                      `json:"triggerResetActions"`
}

// GetActions returns AlertDefinitionInput.Actions, and is useful for accessing the field via an interface.
func (v *AlertDefinitionInput) GetActions() []AlertActionInput { return v.Actions }

// GetCondition returns AlertDefinitionInput.Condition, and is useful for accessing the field via an interface.
func (v *AlertDefinitionInput) GetCondition() []AlertConditionNodeInput { return v.Condition }

// GetDescription returns AlertDefinitionInput.Description, and is useful for accessing the field via an interface.
func (v *AlertDefinitionInput) GetDescription() string { return v.Description }

// GetEnabled returns AlertDefinitionInput.Enabled, and is useful for accessing the field via an interface.
func (v *AlertDefinitionInput) GetEnabled() bool { return v.Enabled }

// GetName returns AlertDefinitionInput.Name, and is useful for accessing the field via an interface.
func (v *AlertDefinitionInput) GetName() string { return v.Name }

// GetSeverity returns AlertDefinitionInput.Severity, and is useful for accessing the field via an interface.
func (v *AlertDefinitionInput) GetSeverity() AlertSeverity { return v.Severity }

// GetTriggerResetActions returns AlertDefinitionInput.TriggerResetActions, and is useful for accessing the field via an interface.
func (v *AlertDefinitionInput) GetTriggerResetActions() bool { return v.TriggerResetActions }

type AlertFilterExpressionInput struct {
	Children       []AlertFilterExpressionInput `json:"children"`
	Operation      FilterOperation              `json:"operation"`
	PropertyName   string                       `json:"propertyName"`
	PropertyValue  string                       `json:"propertyValue"`
	PropertyValues []string                     `json:"propertyValues"`
}

// GetChildren returns AlertFilterExpressionInput.Children, and is useful for accessing the field via an interface.
func (v *AlertFilterExpressionInput) GetChildren() []AlertFilterExpressionInput { return v.Children }

// GetOperation returns AlertFilterExpressionInput.Operation, and is useful for accessing the field via an interface.
func (v *AlertFilterExpressionInput) GetOperation() FilterOperation { return v.Operation }

// GetPropertyName returns AlertFilterExpressionInput.PropertyName, and is useful for accessing the field via an interface.
func (v *AlertFilterExpressionInput) GetPropertyName() string { return v.PropertyName }

// GetPropertyValue returns AlertFilterExpressionInput.PropertyValue, and is useful for accessing the field via an interface.
func (v *AlertFilterExpressionInput) GetPropertyValue() string { return v.PropertyValue }

// GetPropertyValues returns AlertFilterExpressionInput.PropertyValues, and is useful for accessing the field via an interface.
func (v *AlertFilterExpressionInput) GetPropertyValues() []string { return v.PropertyValues }

type AlertFilterInput struct {
	ActionConfigurationId string                     `json:"actionConfigurationId"`
	ConditionTypes        []ConditionType            `json:"conditionTypes"`
	Enabled               bool                       `json:"enabled"`
	Entities              []string                   `json:"entities"`
	EntityTypes           []string                   `json:"entityTypes"`
	Filter                AlertFilterExpressionInput `json:"filter"`
	Id                    string                     `json:"id"`
	Name                  string                     `json:"name"`
	Severities            []AlertSeverity            `json:"severities"`
	Triggered             bool                       `json:"triggered"`
	UserId                string                     `json:"userId"`
}

// GetActionConfigurationId returns AlertFilterInput.ActionConfigurationId, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetActionConfigurationId() string { return v.ActionConfigurationId }

// GetConditionTypes returns AlertFilterInput.ConditionTypes, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetConditionTypes() []ConditionType { return v.ConditionTypes }

// GetEnabled returns AlertFilterInput.Enabled, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetEnabled() bool { return v.Enabled }

// GetEntities returns AlertFilterInput.Entities, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetEntities() []string { return v.Entities }

// GetEntityTypes returns AlertFilterInput.EntityTypes, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetEntityTypes() []string { return v.EntityTypes }

// GetFilter returns AlertFilterInput.Filter, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetFilter() AlertFilterExpressionInput { return v.Filter }

// GetId returns AlertFilterInput.Id, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetId() string { return v.Id }

// GetName returns AlertFilterInput.Name, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetName() string { return v.Name }

// GetSeverities returns AlertFilterInput.Severities, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetSeverities() []AlertSeverity { return v.Severities }

// GetTriggered returns AlertFilterInput.Triggered, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetTriggered() bool { return v.Triggered }

// GetUserId returns AlertFilterInput.UserId, and is useful for accessing the field via an interface.
func (v *AlertFilterInput) GetUserId() string { return v.UserId }

type AlertSeverity string

const (
	AlertSeverityCritical AlertSeverity = "CRITICAL"
	AlertSeverityInfo     AlertSeverity = "INFO"
	AlertSeverityWarning  AlertSeverity = "WARNING"
)

type ConditionType string

const (
	ConditionTypeEntityMetric     ConditionType = "ENTITY_METRIC"
	ConditionTypeLogQuery         ConditionType = "LOG_QUERY"
	ConditionTypeStandaloneMetric ConditionType = "STANDALONE_METRIC"
	ConditionTypeUnknown          ConditionType = "UNKNOWN"
)

// CreateAlertDefinitionAlertMutations includes the requested fields of the GraphQL type AlertMutations.
type CreateAlertDefinitionAlertMutations struct {
	CreateAlertDefinition CreateAlertDefinitionAlertMutationsCreateAlertDefinition `json:"createAlertDefinition"`
}

// GetCreateAlertDefinition returns CreateAlertDefinitionAlertMutations.CreateAlertDefinition, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutations) GetCreateAlertDefinition() CreateAlertDefinitionAlertMutationsCreateAlertDefinition {
	return v.CreateAlertDefinition
}

// CreateAlertDefinitionAlertMutationsCreateAlertDefinition includes the requested fields of the GraphQL type AlertDefinition.
type CreateAlertDefinitionAlertMutationsCreateAlertDefinition struct {
	Actions        []CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction                        `json:"actions"`
	FlatCondition  []CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression `json:"flatCondition"`
	Description    string                                                                                              `json:"description"`
	Enabled        bool                                                                                                `json:"enabled"`
	Id             string                                                                                              `json:"id"`
	Name           string                                                                                              `json:"name"`
	OrganizationId string                                                                                              `json:"organizationId"`
	Severity       AlertSeverity                                                                                       `json:"severity"`
}

// GetActions returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Actions, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetActions() []CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction {
	return v.Actions
}

// GetFlatCondition returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.FlatCondition, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetFlatCondition() []CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression {
	return v.FlatCondition
}

// GetDescription returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Description, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetDescription() string {
	return v.Description
}

// GetEnabled returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Enabled, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetEnabled() bool {
	return v.Enabled
}

// GetId returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Id, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetId() string { return v.Id }

// GetName returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Name, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetName() string { return v.Name }

// GetOrganizationId returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.OrganizationId, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetOrganizationId() string {
	return v.OrganizationId
}

// GetSeverity returns CreateAlertDefinitionAlertMutationsCreateAlertDefinition.Severity, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinition) GetSeverity() AlertSeverity {
	return v.Severity
}

// CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction includes the requested fields of the GraphQL type AlertAction.
type CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction struct {
	ConfigurationIds []string `json:"configurationIds"`
	Type             string   `json:"type"`
}

// GetConfigurationIds returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction.ConfigurationIds, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction) GetConfigurationIds() []string {
	return v.ConfigurationIds
}

// GetType returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction.Type, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionActionsAlertAction) GetType() string {
	return v.Type
}

// CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression includes the requested fields of the GraphQL type FlatAlertConditionExpression.
type CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression struct {
	Id string `json:"id"`
}

// GetId returns CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression.Id, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionAlertMutationsCreateAlertDefinitionFlatConditionFlatAlertConditionExpression) GetId() string {
	return v.Id
}

// CreateAlertDefinitionResponse is returned by CreateAlertDefinition on success.
type CreateAlertDefinitionResponse struct {
	AlertMutations CreateAlertDefinitionAlertMutations `json:"alertMutations"`
}

// GetAlertMutations returns CreateAlertDefinitionResponse.AlertMutations, and is useful for accessing the field via an interface.
func (v *CreateAlertDefinitionResponse) GetAlertMutations() CreateAlertDefinitionAlertMutations {
	return v.AlertMutations
}

// DeleteAlertDefinitionAlertMutations includes the requested fields of the GraphQL type AlertMutations.
type DeleteAlertDefinitionAlertMutations struct {
	DeleteAlertDefinition string `json:"deleteAlertDefinition"`
}

// GetDeleteAlertDefinition returns DeleteAlertDefinitionAlertMutations.DeleteAlertDefinition, and is useful for accessing the field via an interface.
func (v *DeleteAlertDefinitionAlertMutations) GetDeleteAlertDefinition() string {
	return v.DeleteAlertDefinition
}

// DeleteAlertDefinitionResponse is returned by DeleteAlertDefinition on success.
type DeleteAlertDefinitionResponse struct {
	AlertMutations DeleteAlertDefinitionAlertMutations `json:"alertMutations"`
}

// GetAlertMutations returns DeleteAlertDefinitionResponse.AlertMutations, and is useful for accessing the field via an interface.
func (v *DeleteAlertDefinitionResponse) GetAlertMutations() DeleteAlertDefinitionAlertMutations {
	return v.AlertMutations
}

type FilterOperation string

const (
	FilterOperationAnd      FilterOperation = "AND"
	FilterOperationContains FilterOperation = "CONTAINS"
	FilterOperationEq       FilterOperation = "EQ"
	FilterOperationExists   FilterOperation = "EXISTS"
	FilterOperationGe       FilterOperation = "GE"
	FilterOperationGt       FilterOperation = "GT"
	FilterOperationIn       FilterOperation = "IN"
	FilterOperationLe       FilterOperation = "LE"
	FilterOperationLt       FilterOperation = "LT"
	FilterOperationMatches  FilterOperation = "MATCHES"
	FilterOperationNe       FilterOperation = "NE"
	FilterOperationNot      FilterOperation = "NOT"
	FilterOperationOr       FilterOperation = "OR"
)

// GetAlertDefinitionsAlertQueries includes the requested fields of the GraphQL type AlertQueries.
type GetAlertDefinitionsAlertQueries struct {
	AlertDefinitions GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResult `json:"alertDefinitions"`
}

// GetAlertDefinitions returns GetAlertDefinitionsAlertQueries.AlertDefinitions, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueries) GetAlertDefinitions() GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResult {
	return v.AlertDefinitions
}

// GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResult includes the requested fields of the GraphQL type AlertDefinitionsResult.
type GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResult struct {
	AlertDefinitions []GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition `json:"alertDefinitions"`
}

// GetAlertDefinitions returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResult.AlertDefinitions, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResult) GetAlertDefinitions() []GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition {
	return v.AlertDefinitions
}

// GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition includes the requested fields of the GraphQL type AlertDefinition.
type GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition struct {
	Actions             []GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction                        `json:"actions"`
	TriggerResetActions bool                                                                                                                                            `json:"triggerResetActions"`
	ConditionType       ConditionType                                                                                                                                   `json:"conditionType"`
	FlatCondition       []GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression `json:"flatCondition"`
	Description         string                                                                                                                                          `json:"description"`
	Enabled             bool                                                                                                                                            `json:"enabled"`
	Id                  string                                                                                                                                          `json:"id"`
	Name                string                                                                                                                                          `json:"name"`
	OrganizationId      string                                                                                                                                          `json:"organizationId"`
	Severity            AlertSeverity                                                                                                                                   `json:"severity"`
	Triggered           bool                                                                                                                                            `json:"triggered"`
	TriggeredTime       string                                                                                                                                          `json:"triggeredTime"`
	TargetEntityTypes   []string                                                                                                                                        `json:"targetEntityTypes"`
	MuteInfo            GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo                                    `json:"muteInfo"`
	UserId              string                                                                                                                                          `json:"userId"`
}

// GetActions returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Actions, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetActions() []GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction {
	return v.Actions
}

// GetTriggerResetActions returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.TriggerResetActions, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetTriggerResetActions() bool {
	return v.TriggerResetActions
}

// GetConditionType returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.ConditionType, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetConditionType() ConditionType {
	return v.ConditionType
}

// GetFlatCondition returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.FlatCondition, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetFlatCondition() []GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression {
	return v.FlatCondition
}

// GetDescription returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Description, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetDescription() string {
	return v.Description
}

// GetEnabled returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Enabled, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetEnabled() bool {
	return v.Enabled
}

// GetId returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Id, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetId() string {
	return v.Id
}

// GetName returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Name, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetName() string {
	return v.Name
}

// GetOrganizationId returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.OrganizationId, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetOrganizationId() string {
	return v.OrganizationId
}

// GetSeverity returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Severity, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetSeverity() AlertSeverity {
	return v.Severity
}

// GetTriggered returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.Triggered, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetTriggered() bool {
	return v.Triggered
}

// GetTriggeredTime returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.TriggeredTime, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetTriggeredTime() string {
	return v.TriggeredTime
}

// GetTargetEntityTypes returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.TargetEntityTypes, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetTargetEntityTypes() []string {
	return v.TargetEntityTypes
}

// GetMuteInfo returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.MuteInfo, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetMuteInfo() GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo {
	return v.MuteInfo
}

// GetUserId returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition.UserId, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinition) GetUserId() string {
	return v.UserId
}

// GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction includes the requested fields of the GraphQL type AlertAction.
type GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction struct {
	ConfigurationIds []string `json:"configurationIds"`
	Type             string   `json:"type"`
}

// GetConfigurationIds returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction.ConfigurationIds, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction) GetConfigurationIds() []string {
	return v.ConfigurationIds
}

// GetType returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction.Type, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionActionsAlertAction) GetType() string {
	return v.Type
}

// GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression includes the requested fields of the GraphQL type FlatAlertConditionExpression.
type GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression struct {
	Id    string                                                                                                                                                                   `json:"id"`
	Links []GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks           `json:"links"`
	Value GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode `json:"value"`
}

// GetId returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression.Id, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression) GetId() string {
	return v.Id
}

// GetLinks returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression.Links, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression) GetLinks() []GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks {
	return v.Links
}

// GetValue returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression.Value, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpression) GetValue() GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode {
	return v.Value
}

// GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks includes the requested fields of the GraphQL type NamedLinks.
type GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks struct {
	Name   string   `json:"name"`
	Values []string `json:"values"`
}

// GetName returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks.Name, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks) GetName() string {
	return v.Name
}

// GetValues returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks.Values, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionLinksNamedLinks) GetValues() []string {
	return v.Values
}

// GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode includes the requested fields of the GraphQL type FlatAlertConditionNode.
type GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode struct {
	FieldName string `json:"fieldName"`
	Operator  string `json:"operator"`
	Type      string `json:"type"`
	Query     string `json:"query"`
}

// GetFieldName returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.FieldName, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetFieldName() string {
	return v.FieldName
}

// GetOperator returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Operator, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetOperator() string {
	return v.Operator
}

// GetType returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Type, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetType() string {
	return v.Type
}

// GetQuery returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode.Query, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionFlatConditionFlatAlertConditionExpressionValueFlatAlertConditionNode) GetQuery() string {
	return v.Query
}

// GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo includes the requested fields of the GraphQL type AlertDefinitionMuteInfo.
type GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo struct {
	Muted bool   `json:"muted"`
	Until string `json:"until"`
}

// GetMuted returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo.Muted, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo) GetMuted() bool {
	return v.Muted
}

// GetUntil returns GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo.Until, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsAlertQueriesAlertDefinitionsAlertDefinitionsResultAlertDefinitionsAlertDefinitionMuteInfo) GetUntil() string {
	return v.Until
}

// GetAlertDefinitionsResponse is returned by GetAlertDefinitions on success.
type GetAlertDefinitionsResponse struct {
	AlertQueries GetAlertDefinitionsAlertQueries `json:"alertQueries"`
}

// GetAlertQueries returns GetAlertDefinitionsResponse.AlertQueries, and is useful for accessing the field via an interface.
func (v *GetAlertDefinitionsResponse) GetAlertQueries() GetAlertDefinitionsAlertQueries {
	return v.AlertQueries
}

type PagingInput struct {
	After  string `json:"after"`
	Before string `json:"before"`
	First  int    `json:"first"`
	Last   int    `json:"last"`
}

// GetAfter returns PagingInput.After, and is useful for accessing the field via an interface.
func (v *PagingInput) GetAfter() string { return v.After }

// GetBefore returns PagingInput.Before, and is useful for accessing the field via an interface.
func (v *PagingInput) GetBefore() string { return v.Before }

// GetFirst returns PagingInput.First, and is useful for accessing the field via an interface.
func (v *PagingInput) GetFirst() int { return v.First }

// GetLast returns PagingInput.Last, and is useful for accessing the field via an interface.
func (v *PagingInput) GetLast() int { return v.Last }

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

type SortInput struct {
	Sorts []SortItemInput `json:"sorts"`
}

// GetSorts returns SortInput.Sorts, and is useful for accessing the field via an interface.
func (v *SortInput) GetSorts() []SortItemInput { return v.Sorts }

type SortItemInput struct {
	Direction    SortDirection `json:"direction"`
	PropertyName string        `json:"propertyName"`
}

// GetDirection returns SortItemInput.Direction, and is useful for accessing the field via an interface.
func (v *SortItemInput) GetDirection() SortDirection { return v.Direction }

// GetPropertyName returns SortItemInput.PropertyName, and is useful for accessing the field via an interface.
func (v *SortItemInput) GetPropertyName() string { return v.PropertyName }

// UpdateAlertDefinitionAlertMutations includes the requested fields of the GraphQL type AlertMutations.
type UpdateAlertDefinitionAlertMutations struct {
	UpdateAlertDefinition UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition `json:"updateAlertDefinition"`
}

// GetUpdateAlertDefinition returns UpdateAlertDefinitionAlertMutations.UpdateAlertDefinition, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutations) GetUpdateAlertDefinition() UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition {
	return v.UpdateAlertDefinition
}

// UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition includes the requested fields of the GraphQL type AlertDefinition.
type UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition struct {
	Actions           []UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction                        `json:"actions"`
	FlatCondition     []UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionFlatConditionFlatAlertConditionExpression `json:"flatCondition"`
	Description       string                                                                                              `json:"description"`
	Enabled           bool                                                                                                `json:"enabled"`
	Id                string                                                                                              `json:"id"`
	MuteInfo          UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionMuteInfo                                    `json:"muteInfo"`
	Name              string                                                                                              `json:"name"`
	OrganizationId    string                                                                                              `json:"organizationId"`
	Severity          AlertSeverity                                                                                       `json:"severity"`
	Triggered         bool                                                                                                `json:"triggered"`
	TriggeredTime     string                                                                                              `json:"triggeredTime"`
	TargetEntityTypes []string                                                                                            `json:"targetEntityTypes"`
	UserId            string                                                                                              `json:"userId"`
}

// GetActions returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Actions, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetActions() []UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction {
	return v.Actions
}

// GetFlatCondition returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.FlatCondition, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetFlatCondition() []UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionFlatConditionFlatAlertConditionExpression {
	return v.FlatCondition
}

// GetDescription returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Description, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetDescription() string {
	return v.Description
}

// GetEnabled returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Enabled, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetEnabled() bool {
	return v.Enabled
}

// GetId returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Id, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetId() string { return v.Id }

// GetMuteInfo returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.MuteInfo, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetMuteInfo() UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionMuteInfo {
	return v.MuteInfo
}

// GetName returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Name, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetName() string { return v.Name }

// GetOrganizationId returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.OrganizationId, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetOrganizationId() string {
	return v.OrganizationId
}

// GetSeverity returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Severity, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetSeverity() AlertSeverity {
	return v.Severity
}

// GetTriggered returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.Triggered, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetTriggered() bool {
	return v.Triggered
}

// GetTriggeredTime returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.TriggeredTime, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetTriggeredTime() string {
	return v.TriggeredTime
}

// GetTargetEntityTypes returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.TargetEntityTypes, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetTargetEntityTypes() []string {
	return v.TargetEntityTypes
}

// GetUserId returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition.UserId, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinition) GetUserId() string {
	return v.UserId
}

// UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction includes the requested fields of the GraphQL type AlertAction.
type UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction struct {
	ConfigurationIds []string `json:"configurationIds"`
	Type             string   `json:"type"`
}

// GetConfigurationIds returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction.ConfigurationIds, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction) GetConfigurationIds() []string {
	return v.ConfigurationIds
}

// GetType returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction.Type, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionActionsAlertAction) GetType() string {
	return v.Type
}

// UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionFlatConditionFlatAlertConditionExpression includes the requested fields of the GraphQL type FlatAlertConditionExpression.
type UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionFlatConditionFlatAlertConditionExpression struct {
	Id string `json:"id"`
}

// GetId returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionFlatConditionFlatAlertConditionExpression.Id, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionFlatConditionFlatAlertConditionExpression) GetId() string {
	return v.Id
}

// UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionMuteInfo includes the requested fields of the GraphQL type AlertDefinitionMuteInfo.
type UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionMuteInfo struct {
	Muted bool   `json:"muted"`
	Until string `json:"until"`
}

// GetMuted returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionMuteInfo.Muted, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionMuteInfo) GetMuted() bool {
	return v.Muted
}

// GetUntil returns UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionMuteInfo.Until, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionAlertMutationsUpdateAlertDefinitionMuteInfo) GetUntil() string {
	return v.Until
}

// UpdateAlertDefinitionResponse is returned by UpdateAlertDefinition on success.
type UpdateAlertDefinitionResponse struct {
	AlertMutations UpdateAlertDefinitionAlertMutations `json:"alertMutations"`
}

// GetAlertMutations returns UpdateAlertDefinitionResponse.AlertMutations, and is useful for accessing the field via an interface.
func (v *UpdateAlertDefinitionResponse) GetAlertMutations() UpdateAlertDefinitionAlertMutations {
	return v.AlertMutations
}

// __CreateAlertDefinitionInput is used internally by genqlient
type __CreateAlertDefinitionInput struct {
	Definition AlertDefinitionInput `json:"definition"`
}

// GetDefinition returns __CreateAlertDefinitionInput.Definition, and is useful for accessing the field via an interface.
func (v *__CreateAlertDefinitionInput) GetDefinition() AlertDefinitionInput { return v.Definition }

// __DeleteAlertDefinitionInput is used internally by genqlient
type __DeleteAlertDefinitionInput struct {
	DeleteAlertDefinitionId string `json:"deleteAlertDefinitionId"`
}

// GetDeleteAlertDefinitionId returns __DeleteAlertDefinitionInput.DeleteAlertDefinitionId, and is useful for accessing the field via an interface.
func (v *__DeleteAlertDefinitionInput) GetDeleteAlertDefinitionId() string {
	return v.DeleteAlertDefinitionId
}

// __GetAlertDefinitionsInput is used internally by genqlient
type __GetAlertDefinitionsInput struct {
	Filter AlertFilterInput `json:"filter"`
	Paging PagingInput      `json:"paging"`
	SortBy SortInput        `json:"sortBy"`
}

// GetFilter returns __GetAlertDefinitionsInput.Filter, and is useful for accessing the field via an interface.
func (v *__GetAlertDefinitionsInput) GetFilter() AlertFilterInput { return v.Filter }

// GetPaging returns __GetAlertDefinitionsInput.Paging, and is useful for accessing the field via an interface.
func (v *__GetAlertDefinitionsInput) GetPaging() PagingInput { return v.Paging }

// GetSortBy returns __GetAlertDefinitionsInput.SortBy, and is useful for accessing the field via an interface.
func (v *__GetAlertDefinitionsInput) GetSortBy() SortInput { return v.SortBy }

// __UpdateAlertDefinitionInput is used internally by genqlient
type __UpdateAlertDefinitionInput struct {
	Definition              AlertDefinitionInput `json:"definition"`
	UpdateAlertDefinitionId string               `json:"updateAlertDefinitionId"`
}

// GetDefinition returns __UpdateAlertDefinitionInput.Definition, and is useful for accessing the field via an interface.
func (v *__UpdateAlertDefinitionInput) GetDefinition() AlertDefinitionInput { return v.Definition }

// GetUpdateAlertDefinitionId returns __UpdateAlertDefinitionInput.UpdateAlertDefinitionId, and is useful for accessing the field via an interface.
func (v *__UpdateAlertDefinitionInput) GetUpdateAlertDefinitionId() string {
	return v.UpdateAlertDefinitionId
}

func CreateAlertDefinition(
	ctx context.Context,
	client graphql.Client,
	definition AlertDefinitionInput,
) (*CreateAlertDefinitionResponse, error) {
	req := &graphql.Request{
		OpName: "CreateAlertDefinition",
		Query: `
mutation CreateAlertDefinition ($definition: AlertDefinitionInput!) {
	alertMutations {
		createAlertDefinition(definition: $definition) {
			actions {
				configurationIds
				type
			}
			flatCondition {
				id
			}
			description
			enabled
			id
			name
			organizationId
			severity
		}
	}
}
`,
		Variables: &__CreateAlertDefinitionInput{
			Definition: definition,
		},
	}
	var err error

	var data CreateAlertDefinitionResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func DeleteAlertDefinition(
	ctx context.Context,
	client graphql.Client,
	deleteAlertDefinitionId string,
) (*DeleteAlertDefinitionResponse, error) {
	req := &graphql.Request{
		OpName: "DeleteAlertDefinition",
		Query: `
mutation DeleteAlertDefinition ($deleteAlertDefinitionId: ID!) {
	alertMutations {
		deleteAlertDefinition(id: $deleteAlertDefinitionId)
	}
}
`,
		Variables: &__DeleteAlertDefinitionInput{
			DeleteAlertDefinitionId: deleteAlertDefinitionId,
		},
	}
	var err error

	var data DeleteAlertDefinitionResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetAlertDefinitions(
	ctx context.Context,
	client graphql.Client,
	filter AlertFilterInput,
	paging PagingInput,
	sortBy SortInput,
) (*GetAlertDefinitionsResponse, error) {
	req := &graphql.Request{
		OpName: "GetAlertDefinitions",
		Query: `
query GetAlertDefinitions ($filter: AlertFilterInput!, $paging: PagingInput, $sortBy: SortInput) {
	alertQueries {
		alertDefinitions(filter: $filter, paging: $paging, sortBy: $sortBy) {
			alertDefinitions {
				actions {
					configurationIds
					type
				}
				triggerResetActions
				conditionType
				flatCondition {
					id
					links {
						name
						values
					}
					value {
						fieldName
						operator
						type
						query
					}
				}
				description
				enabled
				id
				name
				organizationId
				severity
				triggered
				triggeredTime
				targetEntityTypes
				muteInfo {
					muted
					until
				}
				userId
			}
		}
	}
}
`,
		Variables: &__GetAlertDefinitionsInput{
			Filter: filter,
			Paging: paging,
			SortBy: sortBy,
		},
	}
	var err error

	var data GetAlertDefinitionsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func UpdateAlertDefinition(
	ctx context.Context,
	client graphql.Client,
	definition AlertDefinitionInput,
	updateAlertDefinitionId string,
) (*UpdateAlertDefinitionResponse, error) {
	req := &graphql.Request{
		OpName: "UpdateAlertDefinition",
		Query: `
mutation UpdateAlertDefinition ($definition: AlertDefinitionInput!, $updateAlertDefinitionId: ID!) {
	alertMutations {
		updateAlertDefinition(definition: $definition, id: $updateAlertDefinitionId) {
			actions {
				configurationIds
				type
			}
			flatCondition {
				id
			}
			description
			enabled
			id
			muteInfo {
				muted
				until
			}
			name
			organizationId
			severity
			triggered
			triggeredTime
			targetEntityTypes
			userId
		}
	}
}
`,
		Variables: &__UpdateAlertDefinitionInput{
			Definition:              definition,
			UpdateAlertDefinitionId: updateAlertDefinitionId,
		},
	}
	var err error

	var data UpdateAlertDefinitionResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
